### ISSUE TITLE
lookup() vectorization

### ISSUE THREAD

**Issue by labouz** [CTN-0094/DOPE#3]
function only works with dots (sequence of strings), does not work when a vector is passed.

**Comment by labouz** [comment]
@nathan-castor will write tests with `{testthat}` pacakge. 
- lookup(c("dope", "shrooms"))
- lookup("dope", "shrooms")

lookup(c("dope", "shrooms"), "pot") --> this should go in the documentation as `\dontrun{}`, right @RaymondBalise @gabrielodom ?

**Comment by gabrielodom** [comment]
I would include it as a test, but not an example
