### ISSUE TITLE
problem with version 2.0 CRAN submission

### ISSUE THREAD

**Issue by RaymondBalise** [CTN-0094/DOPE#36]
The URL on line 20 of dea_street_names.Rmd not exist any more:
```
"DIR-020-17 Drug Slang Code Words.pdf" was downloaded from https://www.dea.gov/documents/2017/05/01 on 2020-09-08
```
CRAN says:    
> Please change http --> https, add trailing slashes, or follow moved content as appropriate.

I don't know how to escape/fix that issue.  That was the URL.  

I think the file currently lives here:
https://www.dea.gov/sites/default/files/2018-07/DIR-020-17%20Drug%20Slang%20Code%20Words.pdf

The CRAN guidelines give a bit of a hint here: https://cran.r-project.org/web/packages/URL_checks.html saying that we can include an explanation in the submission.   However, I think we could try the change that line (and line 21) to the content below which provides an audit trail and helps track the current location.

```
"DIR-020-17 Drug Slang Code Words.pdf" was downloaded from https://www.dea.gov/ on 2020-09-08 but the full path
`documents/2017/05/01` no longer exists.

We believe the original file can be found here:
https://www.dea.gov/sites/default/files/2018-07/DIR-020-17%20Drug%20Slang%20Code%20Words.pdf

The file name was changed to remove the spaces (which appear as %20) in the link above.
```

Gabriel, if you think this is okay can you please tweak the Rmd file and resubmit.  Given that CRAN blocked the submission I think we can keep the same version number.  Just be sure to rebuild the docs.

**Comment by gabrielodom** [comment]
Working on it now

**Comment by gabrielodom** [comment]
@RaymondBalise and @labouz, for this vignette we set `eval = FALSE` globally (which I guess is fine), but that vignette calls for a data set `"../inst/extdata/DIR-020-17DrugSlangCodeWords.pdf"` which we do not include in the package, but we also don't explain why it isn't included in the package.
That's a problem, right?
